version: '3.8'

services:
  db:
    container_name: postgres_fastapi_weather
    image: postgres:15-alpine
    privileged: true
    restart: "on-failure"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PORT}:${PORT}